# Generated by Django 5.0.6 on 2024-05-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubecredentials',
            name='refresh_token',
            field=models.CharField(max_length=255),
        ),
    ]
