# Generated by Django 5.0.6 on 2024-05-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_youtubecredentials_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify_token',
            name='access_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='spotify_token',
            name='refresh_token',
            field=models.CharField(max_length=500),
        ),
    ]
