# Generated by Django 5.0.6 on 2024-05-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_youtubecredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubecredentials',
            name='refresh_token',
        ),
    ]
