# Generated by Django 4.2.14 on 2026-03-18 14:02

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_spotify_token_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify_token',
            name='access_token',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=500)),
        ),
        migrations.AlterField(
            model_name='spotify_token',
            name='refresh_token',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=500)),
        ),
        migrations.AlterField(
            model_name='youtubecredentials',
            name='access_token',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='youtubecredentials',
            name='refresh_token',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
