# Generated by Django 4.2.14 on 2026-03-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transferjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferjob',
            name='processed_count',
            field=models.IntegerField(default=0),
        ),
    ]
