# Generated by Django 4.2.14 on 2026-03-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_youtubecredentials_client_fields'),
        ('core', '0006_transferjob_processed_count'),
    ]

    operations = [
    ]
